global:
  scrape_interval: 5s
  evaluation_interval: 15s

  external_labels:
    monitor: "bytelearn-flask-assignment"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - alertmanager:9093

rule_files:

scrape_configs:
  - job_name: "heroku-flask-app"

    static_configs:
      - targets: ["bytelearn-flask-assignment.herokuapp.com"]
